-- ============================================
-- RESTORE ALL DATA FROM EXPORT
-- Run this in Supabase SQL Editor
-- ============================================

-- This will restore:
-- - 121 products with correct stock quantities and prices
-- - 58 customers with correct details
-- ============================================

BEGIN;

UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE products SET 
UPDATE customers SET
UPDATE customers SET
UPDATE customers SET
UPDATE customers SET
UPDATE customers SET
UPDATE customers SET
UPDATE customers SET
UPDATE customers SET
UPDATE customers SET
UPDATE customers SET
UPDATE customers SET
UPDATE customers SET
UPDATE customers SET
UPDATE customers SET
UPDATE customers SET
UPDATE customers SET
UPDATE customers SET
UPDATE customers SET
UPDATE customers SET
UPDATE customers SET
UPDATE customers SET
UPDATE customers SET
UPDATE customers SET
UPDATE customers SET
UPDATE customers SET
UPDATE customers SET
UPDATE customers SET
UPDATE customers SET
UPDATE customers SET
UPDATE customers SET
UPDATE customers SET
UPDATE customers SET
UPDATE customers SET
UPDATE customers SET
UPDATE customers SET
UPDATE customers SET
UPDATE customers SET
UPDATE customers SET
UPDATE customers SET
UPDATE customers SET
UPDATE customers SET
UPDATE customers SET
UPDATE customers SET
UPDATE customers SET
UPDATE customers SET
UPDATE customers SET
UPDATE customers SET
UPDATE customers SET
UPDATE customers SET
UPDATE customers SET
UPDATE customers SET
UPDATE customers SET
UPDATE customers SET
UPDATE customers SET


COMMIT;

-- ✅ Data restored! Refresh your app.
